image: node:8.1.4

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - npm install
            # Create a build
            - npm run build
          artifacts:
            - public/**
      - step:
          script:
            # Downloading the Google Cloud SDK
            - curl -o /tmp/google-cloud-sdk.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-155.0.0-linux-x86_64.tar.gz
            - tar -xvf /tmp/google-cloud-sdk.tar.gz -C /tmp/
            - /tmp/google-cloud-sdk/install.sh -q
            - source /tmp/google-cloud-sdk/path.bash.inc
            # Authenticating with the service account key file
            - echo $GCLOUD_API_KEYFILE | base64 --decode --ignore-garbage > ./gcloud-api-key.json
            - gcloud auth activate-service-account --key-file gcloud-api-key.json
            # Deploy build folder to the bucket configured in pipelines variables
            # -m use faster multithreaded uploads
            # -d delete remote files that aren't in the source
            # -r recurse into source subdirectories
            - gsutil -m rsync -d -r ./public $GCLOUD_PROJECT
