backend:
  name: github
  repo: homearanya/testing-site # Path to your Bitbucket repository
  branch: master

media_folder: static/img
public_folder: /img
site_url: https://docs-vuukle.netlify.com
logo_url: https://docs-vuukle.netlify.com/vuukle-logo.svg
show_preview_links: true

collections:
  - name: articles
    label: Articles
    label_singular: Article
    folder: 'src/content/articles'
    create: true
    slug: {{slug}}
    preview_path: {{slug}}
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Path',
          name: 'path',
          widget: 'string',
          required: false,
          hint: 'A path will be created out of the title. Here you can create your own. Follow this pattern: "/this-is-my-own-path/"',
        }
      - { label: 'Published Date', name: 'date', widget: 'date', dateFormat: 'YYYY-MM-DD' }
      # - {
      #     label: 'Category',
      #     name: 'category',
      #     widget: 'text',
      # }
      - {
          label: 'Category',
          name: 'category',
          widget: 'relation',
          collection: 'categories',
          searchFields: ['title'],
          valueField: 'title',
          displayFields: ['title'],
        }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false, hint: 'Comma-separated tags' }
      - { label: 'Short Description', name: 'shortDescription', widget: 'text', hint: For search engines }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: categories
    label: Categories
    label_singular: Category
    folder: 'src/content/categories'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Short Description', name: 'description', widget: 'text' }
      - { label: 'Icon', name: 'icon', widget: 'image' }
      - { label: 'Display Order', name: 'displayOrder', widget: 'number', valueType: 'int', step: 1 }
